version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_hubspot
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: hubSpot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
